version: '2'
services:
  express:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_express
    ports:
      - ${PORT}:3000
    volumes:
      - .:/workspace/
      - /workspace/node_modules
